version: "3.4"

services:
  scope-demo-akka-http-java:
    build: .
    image: scope/scope-demo-akka-http-java
    environment:
      - CI
      - SCOPE_APIKEY
      - SCOPE_API_ENDPOINT
      - JENKINS_URL
      - CIRCLECI
      - CIRCLE_BUILD_NUM
      - CIRCLE_BUILD_URL
      - BUILD_ID
      - BUILD_NUMBER
      - BUILD_URL
      - GIT_COMMIT=${GIT_COMMIT}
    volumes:
      - ~/.scope:/root/.scope